SELECT TO_CHAR(ADD_MONTHS(LAST_DAY(SYSDATE) + 1, -1) + (LEVEL - 1),
               'yyyy/mm/dd')
  FROM DUAL
CONNECT BY TRUNC(ADD_MONTHS(LAST_DAY(SYSDATE) + 1, -1)) + LEVEL - 1 <=
           TRUNC(LAST_DAY(ADD_MONTHS(LAST_DAY(SYSDATE) + 1, -1)));
