SELECT A.RROUTEDEVID,
       A.DEVID,
       D.DEVNAME,
       A.ROUTEID,
       A.SEGMENTID,
       B.SEGMENTNAME,
       A.STATIONID,
       C.STATIONNAME,
       A.DUALSERIALID
  FROM MCRROUTEDEVICEGS A,
       MCSEGMENTINFOGS  B,
       MCSTATIONINFOGS  C,
       MCDEVICEINFOGS   D
 WHERE A.SEGMENTID = B.SEGMENTID(+)
   AND A.STATIONID = C.STATIONID(+)
   AND A.DEVID = D.ID
   AND A.ROUTEID = '320220'  SELECT * FROM MCROUTEINFOGS
