-----站点报站情况查询
SELECT *
  FROM BSVCBUSARRLFTLD5 BSV, MCROUTEINFOGS R, MCSTATIONINFOGS S
 WHERE BSV.ROUTEID = R.ROUTEID(+)
   AND BSV.STATIONNUM = BSV.ACTDATETIME > DATE '2016-7-16';

SELECT A.ROUTEID,
       R.ROUTENAME,
       SUM(DECODE(A.STATIONSEQNUM, 1, 1, 0)) N1,
       SUM(DECODE(A.STATIONSEQNUM, 2, 1, 0)) N2,
       SUM(DECODE(A.STATIONSEQNUM, 3, 1, 0)) N3,
       SUM(DECODE(A.STATIONSEQNUM,
                  (SELECT MIN(R1.DUALSERIALID)
                     FROM MCRSEGMENTSTATIONGS R1
                    WHERE R1.ROUTEID = A.ROUTEID
                      AND R1.SUBROUTEID = A.SUBROUTEID
                      AND R1.STATIONTYPEID = 6),
                  1,
                  0)) 主上6,
       SUM(DECODE(A.STATIONSEQNUM,
                  (SELECT MIN(R1.DUALSERIALID)
                     FROM MCRSEGMENTSTATIONGS R1
                    WHERE R1.ROUTEID = A.ROUTEID
                      AND R1.SUBROUTEID = A.SUBROUTEID
                      AND R1.STATIONTYPEID = 7),
                  1,
                  0)) 主下7,
       SUM(DECODE(A.STATIONSEQNUM,
                  (SELECT MIN(R1.DUALSERIALID)
                     FROM MCRSEGMENTSTATIONGS R1
                    WHERE R1.ROUTEID = A.ROUTEID
                      AND R1.SUBROUTEID = A.SUBROUTEID
                      AND R1.STATIONTYPEID = 8),
                  1,
                  0)) 副上8,
       SUM(DECODE(A.STATIONSEQNUM,
                  (SELECT MIN(R1.DUALSERIALID)
                     FROM MCRSEGMENTSTATIONGS R1
                    WHERE R1.ROUTEID = A.ROUTEID
                      AND R1.SUBROUTEID = A.SUBROUTEID
                      AND R1.STATIONTYPEID = 9),
                  1,
                  0)) 副下9
  FROM BSVCBUSARRLFTLD5 A, MCROUTEINFOGS R
 WHERE A.ROUTEID = R.ROUTEID(+)
   AND A.ACTDATETIME BETWEEN DATE '2016-7-15' AND DATE
 '2016-7-16'
   AND A.DATATYPE = 4
   AND A.ISARRLFT = 1
   AND (A.STATIONSEQNUM < 4 OR EXISTS
        (SELECT 1
           FROM MCRSEGMENTSTATIONGS R
          WHERE R.ROUTEID = A.ROUTEID
            AND R.SUBROUTEID = A.SUBROUTEID
            AND A.STATIONSEQNUM = R.DUALSERIALID
            AND R.STATIONTYPEID <> 3))
 GROUP BY A.ROUTEID, R.ROUTENAME
 ORDER BY A.ROUTEID;
-------------------------------------------------------------------
SELECT A.ROUTEID,R.ROUTENAME, A.STATIONNUM,s.stationname,COUNT(1)
  FROM BSVCBUSARRLFTLD5 A, MCROUTEINFOGS R, MCSTATIONINFOGS S
 WHERE A.ROUTEID = R.ROUTEID(+)
   AND A.STATIONNUM = S.STATIONNO(+)
   AND A.ACTDATETIME BETWEEN DATE '2016-7-15' AND DATE
 '2016-7-16'
   AND A.DATATYPE = 4
   AND A.ISARRLFT = 1
 GROUP BY A.ROUTEID, R.ROUTENAME, A.STATIONNUM,s.stationname
 ORDER BY A.ROUTEID;
