SELECT *
  FROM BSVCBUSVIOLLD5 B
 WHERE B.PRODUCTID = '111111'
   AND B.ACTDATETIME > DATE '2017-2-15';
SELECT * FROM MENUINFO M WHERE M.PARENTCODE = '11' FOR UPDATE;
SELECT RBM.BUSID, B.BUSSELFID, RBM.PRODUCTID
  FROM MCRBUSBUSMACHINEGS RBM, MCBUSINFOGS B
 WHERE RBM.BUSID = B.BUSID(+)
   AND B.BUSSELFID LIKE '%999%';
SELECT *
  FROM MCROUTEINFOGS R
 WHERE R.ROUTENAME LIKE '92%'
    OR R.ROUTENAME LIKE '49%';
SELECT *
  FROM FDISLOGLD F
 WHERE F.ROUTEID IN ('620490', '620920')
   AND F.BUSSELFID = '6-7511'
   AND F.REALLEAVETIME > DATE '2017-2-15';
SELECT SUBSTR(TO_CHAR(F.SENDTIME, 'yyyy-mm-dd hh24:mi:ss'), 0, 13),
       F.CMDTYPE,
       B.BUSSELFID
  FROM FDISDISCMDRECGD F, MCBUSINFOGS B
 WHERE F.BUSID = B.BUSID
   AND F.ROUTEID IN ('620490', '620920')
   AND F.SENDTIME > DATE '2017-2-15'
   AND F.CMDOPERATETYPE = '系统发送消息'
   AND B.BUSSELFID = '6-7417'
 GROUP BY SUBSTR(TO_CHAR(F.SENDTIME, 'yyyy-mm-dd hh24:mi:ss'), 0, 13),
          F.CMDTYPE,
          B.BUSSELFID;
          SELECT * FROM devevent5 d WHERE d.eventtime>DATE'2017-2-15' AND d.productid='50067417';
          SELECT * FROM Typeentry t WHERE t.typename LIKE '%EVENTTYPE%';
          SELECT * FROM mcstationinfogs s WHERE length(s.stationno)>12;
          SELECT * FROM mcrouteinfogs r WHERE r.routename LIKE '36%';
          SELECT * FROM bsvcbusrundatald5 
