-----线路组织关系表
SELECT R.ROUTEID, R.ROUTENAME, O.ORGID, O.ORGNAME
  FROM MCROUTEINFOGS R, MCRORGROUTEGS RO, MCORGINFOGS O
 WHERE R.ROUTEID = RO.ROUTEID(+)
   AND RO.ORGID = O.ORGID(+)
/*   AND R.ROUTEID = '320570'*/ 
   AND O.ORGID IN
       (SELECT O.ORGID 
          FROM MCORGINFOGS O
         START WITH O.ORGID = (SELECT ORGID
                                 FROM MCORGINFOGS
                                WHERE ORGNAME LIKE '%三公司%')
        CONNECT BY PRIOR O.ORGID = O.PARENTORGID);

-----扩展选择
  SELECT * FROM MCROUTEINFOGS R WHERE R.ROUTENAME LIKE '%57%';
