spool D:\BACKUP\backup\basic\table_name.txt 
set head off 
set feedback off 
set pagesize 1000 
set term off 
select 'tables=' || t.table_name from user_tables t where t.table_name not in 
('BSVCBUSRUNDATALD', 'BSVCBUSRUNDATAER', 'PKG_GETSEQUENCE_LOGS','BSVCBUSRUNDATALD5','DVR_ERRORLOGGS','DVR_ONLINERECORDGD','DVR_ALERTINFOGS','FDISDISPLANLDABNORMITY','FDISDISPATCHLOG','FDISPREDISPLANLD','DEVEVENT5','BSVCDEVMALRPTLD5','UPGRADELOG', 
'INFOPUBPERMANENT','INFOPUBTEMP','LOGMAIN','FDISLOGLD','FDISLOGFORHANDLELD','MCUSERLOGINOUTGS','FDISBIGINTERVALRECGD','BSVCBUSARRLFTLD5','DBLOGSEQ','TUPDATERECORDGS','FDISBUSRUNPROPORTIONLD','DFDISBUSABNORMITYPROCESS','FDISDISCMDRECGD'); 
spool off 
exit; 
